- name: Modify document root in httpd.conf
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^DocumentRoot'
    line: 'DocumentRoot "{{ phpipamhtmldir }}"'
    state: present

- name: Add httpd config file for phpipam
  copy:
    src: /vagrant/ansible/phpipam.conf
    dest: /etc/httpd/conf.d/phpipam.conf
    owner: root
    group: root
    mode: 0644

- name: Setup config.php
  copy:
    src: "{{ phpipamhtmldir }}/config.dist.php"
    dest: "{{ phpipamhtmldir }}/config.php"

- name: Install PIP and Python Development
  yum:
    name: "{{ item }}"
    validate_certs: no
  with_items:
    - python-pip
    - python-devel
    - mysql-devel

- name: Install the Python MySQL module
  pip:
    name: MySQL-python
    extra_args: --trusted-host pypi.python.org

- name: Start httpd, mariadb and set for automatic start
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - httpd
    - mariadb

- name: Setup mariadb - Setup Root Account root:root and Remove Anonymous
  mysql_user:
    check_implicit_admin: yes
    login_user: root
    login_password: root
    name: root
    password: root
    state: present

- name: Setup mariadb - Remove Anonymous User Account
  mysql_user:
    login_user: root
    login_password: root
    name: ''
    state: absent

- name: Initialize phpIPAM DB Install
  uri:
    url: http://localhost:80/app/install/install-execute.php
    method: POST
    body: "mysqlrootuser=root&install_type=install&mysqlrootpass=root&createdb=on&creategrants=on"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
      X-Requested-With: "XMLHttpRequest"
    return_content: yes
  register: database
  failed_when:
    - "'Database installed successfully!' not in database.content"
    - "'Database already installed' not in database.content"

- name: Set phpIPAM admin password -> admin12345
  uri:
    url: http://localhost:80/app/install/postinstall_submit.php
    method: POST
    body: "password1=admin12345&password2=admin12345&siteTitle=phpipam&siteURL="

- name: Post Install Message
  debug:
    msg: "{{ post_install.split('\n') }}"