- hosts: all
  vars:
    post_install: |
      Provision of PHPIpam Base Complete
      To access navigate to 127.0.0.1:8081
      Admin username/password is admin/admin12345
    phpipamhtmldir: /var/www/html/phpipam


  tasks:
  - include_tasks: pre_install_tasks.yml

  - name: Git clone 1.3.1 to {{ phpipamhtmldir }}
    git:
      clone: yes
      repo: https://github.com/phpipam/phpipam.git
      dest: "{{ phpipamhtmldir }}"
      version: 1.3.1
      force: yes

  - include_tasks: post_install_tasks.yml